name: Deploy flasher to Pages

on:
  push:
    branches: ["main"]
    paths: ["flasher/**"]

  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload static files as artifact
        id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: flasher/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
